name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "hello"
  my-other-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-other-step
        run: echo "world"
